name: deploy-authy

on:
  push:
    branches:
      - master
    paths:
      - 'authy/**'
      
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: cd authy && docker build -t 200401073/authy .
        - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        - run: docker push 200401073/authy 
